// Code generated by MockGen. DO NOT EDIT.
// Source: mock_alert.go

// Package mock_analytics is a generated GoMock package.
package analytics

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// SendAnalyticsAlert mocks base method
func (m *MockService) SendAnalyticsAlert(message string) {
	m.ctrl.Call(m, "SendAnalyticsAlert", message)
}

// SendAnalyticsAlert indicates an expected call of SendAnalyticsAlert
func (mr *MockServiceMockRecorder) SendAnalyticsAlert(message interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAnalyticsAlert", reflect.TypeOf((*MockService)(nil).SendAnalyticsAlert), message)
}
