// Code generated by MockGen. DO NOT EDIT.
// Source: ../callout/service.go

// Package callout is a generated GoMock package.
package callout

import (
	gomock "github.com/golang/mock/gomock"
	context "golang.org/x/net/context"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// InvokeCallout mocks base method
func (m *MockService) InvokeCallout(ctx context.Context, chat uint32, title, message string, variables map[string]string) error {
	ret := m.ctrl.Call(m, "InvokeCallout", ctx, chat, title, message, variables)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvokeCallout indicates an expected call of InvokeCallout
func (mr *MockServiceMockRecorder) InvokeCallout(ctx, chat, title, message, variables interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvokeCallout", reflect.TypeOf((*MockService)(nil).InvokeCallout), ctx, chat, title, message, variables)
}
