version: 0.2

env:
  variables:
    DOCKER_USERNAME: weautomateeverything
    IMAGE_NAME: weautomateeverything/go2hal

  parameter-store:
    DOCKER_PASSWORD: docker_password

phases:
  install:
    commands:
    - go get
  pre_build:
    commands:

    finally:

  build:
    commands:
    - CGO_ENABLED=1 GOOS=linux go build -o ./go2hal .
    - swagger generate spec -m -o ./swagger.json
  post_build:
    commands:

    finally:

artifacts:
  files:
  - go2hal
  - swagger.json
cache:
  paths:
