version: 0.2

phases:
  install:
    commands:
    # printenv
    # pwd
    # mkdir -p /go/src/github.com/weAutomateEverything/go2hal
    # cp -R * /go/src/github.com/weAutomateEverything/go2hal/
  pre_build:
    commands:

    finally:

  build:
    commands:
    # cd /go/src/github.com/weAutomateEverything/go2hal
    # pwd
    # ls -al
    - CGO_ENABLED=1 GOOS=linux go build -o ./go2hal .
    - swagger generate spec -m -o ./swagger.json
  post_build:
    commands:

    finally:

artifacts:
  files:
  - go2hal
  - swagger.json
  - Dockerfile
cache:
  paths:
