version: 0.2

phases:
  install:
    commands:
    # printenv
    # pwd
    - mkdir -p /go/src/github.com/weAutomateEverything/go2hal
    - rm -rf /go/src/github.com/weAutomateEverything/go2hal/*
    - cp -R * /go/src/github.com/weAutomateEverything/go2hal/
  pre_build:
    commands:

    finally:

  build:
    commands:
    - go get github.com/weAutomateEverything/go2hal
    - GOOS=linux go build -ldflags '-linkmode=external' -o ./go2hal github.com/weAutomateEverything/go2hal
    - go get -u github.com/go-swagger/go-swagger/cmd/swagger
    - swagger generate spec -m -o ./swagger.json
  post_build:
    commands:

    finally:

artifacts:
  files:
  - go2hal
  - swagger.json
  - Dockerfile
cache:
  paths:
