// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remote_command.proto

/*
Package remoteTelegramCommands is a generated protocol buffer package.

It is generated from these files:
	remote_command.proto

It has these top-level messages:
	RemoteCommandRequest
	RemoteRequest
	Request
	Response
*/
package remoteTelegramCommands

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RemoteCommandRequest struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *RemoteCommandRequest) Reset()                    { *m = RemoteCommandRequest{} }
func (m *RemoteCommandRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoteCommandRequest) ProtoMessage()               {}
func (*RemoteCommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RemoteCommandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoteCommandRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type RemoteRequest struct {
	From    string `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *RemoteRequest) Reset()                    { *m = RemoteRequest{} }
func (m *RemoteRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoteRequest) ProtoMessage()               {}
func (*RemoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RemoteRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *RemoteRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Request struct {
	State     string `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Nextstate string `protobuf:"bytes,2,opt,name=nextstate" json:"nextstate,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Request) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Request) GetNextstate() string {
	if m != nil {
		return m.Nextstate
	}
	return ""
}

type Response struct {
	From    string   `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Message string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Fields  []string `protobuf:"bytes,3,rep,name=fields" json:"fields,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterType((*RemoteCommandRequest)(nil), "remoteTelegramCommands.RemoteCommandRequest")
	proto.RegisterType((*RemoteRequest)(nil), "remoteTelegramCommands.RemoteRequest")
	proto.RegisterType((*Request)(nil), "remoteTelegramCommands.Request")
	proto.RegisterType((*Response)(nil), "remoteTelegramCommands.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RemoteCommand service

type RemoteCommandClient interface {
	RegisterCommand(ctx context.Context, in *RemoteCommandRequest, opts ...grpc.CallOption) (RemoteCommand_RegisterCommandClient, error)
	RegisterCommandLet(ctx context.Context, in *Request, opts ...grpc.CallOption) (RemoteCommand_RegisterCommandLetClient, error)
}

type remoteCommandClient struct {
	cc *grpc.ClientConn
}

func NewRemoteCommandClient(cc *grpc.ClientConn) RemoteCommandClient {
	return &remoteCommandClient{cc}
}

func (c *remoteCommandClient) RegisterCommand(ctx context.Context, in *RemoteCommandRequest, opts ...grpc.CallOption) (RemoteCommand_RegisterCommandClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RemoteCommand_serviceDesc.Streams[0], c.cc, "/remoteTelegramCommands.RemoteCommand/RegisterCommand", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteCommandRegisterCommandClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RemoteCommand_RegisterCommandClient interface {
	Recv() (*RemoteRequest, error)
	grpc.ClientStream
}

type remoteCommandRegisterCommandClient struct {
	grpc.ClientStream
}

func (x *remoteCommandRegisterCommandClient) Recv() (*RemoteRequest, error) {
	m := new(RemoteRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *remoteCommandClient) RegisterCommandLet(ctx context.Context, in *Request, opts ...grpc.CallOption) (RemoteCommand_RegisterCommandLetClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RemoteCommand_serviceDesc.Streams[1], c.cc, "/remoteTelegramCommands.RemoteCommand/RegisterCommandLet", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteCommandRegisterCommandLetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RemoteCommand_RegisterCommandLetClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type remoteCommandRegisterCommandLetClient struct {
	grpc.ClientStream
}

func (x *remoteCommandRegisterCommandLetClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RemoteCommand service

type RemoteCommandServer interface {
	RegisterCommand(*RemoteCommandRequest, RemoteCommand_RegisterCommandServer) error
	RegisterCommandLet(*Request, RemoteCommand_RegisterCommandLetServer) error
}

func RegisterRemoteCommandServer(s *grpc.Server, srv RemoteCommandServer) {
	s.RegisterService(&_RemoteCommand_serviceDesc, srv)
}

func _RemoteCommand_RegisterCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RemoteCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RemoteCommandServer).RegisterCommand(m, &remoteCommandRegisterCommandServer{stream})
}

type RemoteCommand_RegisterCommandServer interface {
	Send(*RemoteRequest) error
	grpc.ServerStream
}

type remoteCommandRegisterCommandServer struct {
	grpc.ServerStream
}

func (x *remoteCommandRegisterCommandServer) Send(m *RemoteRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _RemoteCommand_RegisterCommandLet_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RemoteCommandServer).RegisterCommandLet(m, &remoteCommandRegisterCommandLetServer{stream})
}

type RemoteCommand_RegisterCommandLetServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type remoteCommandRegisterCommandLetServer struct {
	grpc.ServerStream
}

func (x *remoteCommandRegisterCommandLetServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _RemoteCommand_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remoteTelegramCommands.RemoteCommand",
	HandlerType: (*RemoteCommandServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterCommand",
			Handler:       _RemoteCommand_RegisterCommand_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RegisterCommandLet",
			Handler:       _RemoteCommand_RegisterCommandLet_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "remote_command.proto",
}

func init() { proto.RegisterFile("remote_command.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x8d, 0xd5, 0xd6, 0x8c, 0x88, 0x30, 0x84, 0x12, 0x44, 0x30, 0x2c, 0x08, 0x3d, 0x48,
	0x10, 0x3d, 0xf7, 0xe4, 0xb5, 0x07, 0x59, 0xbc, 0x79, 0x90, 0xb5, 0x99, 0x86, 0x48, 0x77, 0x37,
	0xee, 0xac, 0xe0, 0x4f, 0xf5, 0xe7, 0x48, 0xb3, 0xbb, 0x58, 0xa4, 0x15, 0xbc, 0xcd, 0xbc, 0x37,
	0xf3, 0x4d, 0xf2, 0x58, 0x28, 0x1c, 0x69, 0xeb, 0xe9, 0x65, 0x69, 0xb5, 0x56, 0xa6, 0xa9, 0x7b,
	0x67, 0xbd, 0xc5, 0x69, 0x50, 0x9f, 0x68, 0x4d, 0xad, 0x53, 0xfa, 0x21, 0x98, 0x2c, 0x16, 0x50,
	0xc8, 0xc1, 0x89, 0x8a, 0xa4, 0xf7, 0x0f, 0x62, 0x8f, 0x08, 0x47, 0x46, 0x69, 0x2a, 0xb3, 0x2a,
	0x9b, 0xe5, 0x72, 0xa8, 0xb1, 0x82, 0xd3, 0x86, 0x78, 0xe9, 0xba, 0xde, 0x77, 0xd6, 0x94, 0x87,
	0x83, 0xb5, 0x2d, 0x89, 0x39, 0x9c, 0x05, 0xda, 0x16, 0x66, 0xe5, 0xac, 0x4e, 0x98, 0x4d, 0x8d,
	0x25, 0x4c, 0x34, 0x31, 0xab, 0x96, 0x22, 0x22, 0xb5, 0x62, 0x0e, 0x93, 0xb4, 0x58, 0xc0, 0x31,
	0x7b, 0xe5, 0xd3, 0x07, 0x84, 0x06, 0x2f, 0x21, 0x37, 0xf4, 0xe9, 0x83, 0x13, 0x96, 0x7f, 0x04,
	0xf1, 0x08, 0x27, 0x92, 0xb8, 0xb7, 0x86, 0xe9, 0x7f, 0x87, 0x71, 0x0a, 0xe3, 0x55, 0x47, 0xeb,
	0x86, 0xcb, 0x51, 0x35, 0x9a, 0xe5, 0x32, 0x76, 0x77, 0x5f, 0x59, 0xfa, 0xa1, 0x18, 0x0f, 0xbe,
	0xc1, 0xb9, 0xa4, 0xb6, 0x63, 0x4f, 0x2e, 0x49, 0x37, 0xf5, 0xee, 0x6c, 0xeb, 0x5d, 0xc1, 0x5e,
	0x5c, 0xff, 0x3d, 0x1d, 0xc7, 0xc4, 0xc1, 0x6d, 0x86, 0xcf, 0x80, 0xbf, 0x6e, 0x2d, 0xc8, 0xe3,
	0xd5, 0x7e, 0x40, 0xb8, 0x50, 0xed, 0x1f, 0x08, 0xe1, 0x6c, 0xe0, 0xaf, 0xe3, 0xe1, 0x5d, 0xdc,
	0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xcb, 0x54, 0x1e, 0x2f, 0x02, 0x00, 0x00,
}
