# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8000/api/grafana/532350981

{
  "evalMatches": [
    {
      "value": 100,
      "metric": "High value",
      "tags": null
    },
    {
      "value": 200,
      "metric": "Higher Value",
      "tags": null
    }
  ],
  "imageUrl": "http://grafana.org/assets/img/blog/mixed_styles.png",
  "message": "Someone is testing the alert notification within grafana.",
  "ruleId": 0,
  "ruleName": "Test notification",
  "ruleUrl": "http://localhost:3000/",
  "state": "alerting",
  "title": "[Alerting] Test notification"
}

###
