// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_alert is a generated GoMock package.
package alert

import (
	gomock "github.com/golang/mock/gomock"
	telegram "github.com/weAutomateEverything/go2hal/telegram"
	context "golang.org/x/net/context"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// SendAlert mocks base method
func (m *MockService) SendAlert(ctx context.Context, chatId uint32, message string) error {
	ret := m.ctrl.Call(m, "SendAlert", ctx, chatId, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAlert indicates an expected call of SendAlert
func (mr *MockServiceMockRecorder) SendAlert(ctx, chatId, message interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAlert", reflect.TypeOf((*MockService)(nil).SendAlert), ctx, chatId, message)
}

// SendAlertWithReply mocks base method
func (m *MockService) SendAlertWithReply(ctx context.Context, chatId uint32, message, correlationId string) (int, error) {
	ret := m.ctrl.Call(m, "SendAlertWithReply", ctx, chatId, message, correlationId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAlertWithReply indicates an expected call of SendAlertWithReply
func (mr *MockServiceMockRecorder) SendAlertWithReply(ctx, chatId, message, correlationId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAlertWithReply", reflect.TypeOf((*MockService)(nil).SendAlertWithReply), ctx, chatId, message, correlationId)
}

// SendImageToAlertGroup mocks base method
func (m *MockService) SendImageToAlertGroup(ctx context.Context, chatid uint32, image []byte) error {
	ret := m.ctrl.Call(m, "SendImageToAlertGroup", ctx, chatid, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendImageToAlertGroup indicates an expected call of SendImageToAlertGroup
func (mr *MockServiceMockRecorder) SendImageToAlertGroup(ctx, chatid, image interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendImageToAlertGroup", reflect.TypeOf((*MockService)(nil).SendImageToAlertGroup), ctx, chatid, image)
}

// SendDocumentToAlertGroup mocks base method
func (m *MockService) SendDocumentToAlertGroup(ctx context.Context, chatid uint32, document []byte, extension string) error {
	ret := m.ctrl.Call(m, "SendDocumentToAlertGroup", ctx, chatid, document, extension)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDocumentToAlertGroup indicates an expected call of SendDocumentToAlertGroup
func (mr *MockServiceMockRecorder) SendDocumentToAlertGroup(ctx, chatid, document, extension interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDocumentToAlertGroup", reflect.TypeOf((*MockService)(nil).SendDocumentToAlertGroup), ctx, chatid, document, extension)
}

// SendError mocks base method
func (m *MockService) SendError(ctx context.Context, err error) error {
	ret := m.ctrl.Call(m, "SendError", ctx, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendError indicates an expected call of SendError
func (mr *MockServiceMockRecorder) SendError(ctx, err interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendError", reflect.TypeOf((*MockService)(nil).SendError), ctx, err)
}

// SendErrorImage mocks base method
func (m *MockService) SendErrorImage(ctx context.Context, image []byte) error {
	ret := m.ctrl.Call(m, "SendErrorImage", ctx, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendErrorImage indicates an expected call of SendErrorImage
func (mr *MockServiceMockRecorder) SendErrorImage(ctx, image interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendErrorImage", reflect.TypeOf((*MockService)(nil).SendErrorImage), ctx, image)
}

// GetReplies mocks base method
func (m *MockService) GetReplies(ctx context.Context, chatId uint32) ([]telegram.Replies, error) {
	ret := m.ctrl.Call(m, "GetReplies", ctx, chatId)
	ret0, _ := ret[0].([]telegram.Replies)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReplies indicates an expected call of GetReplies
func (mr *MockServiceMockRecorder) GetReplies(ctx, chatId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReplies", reflect.TypeOf((*MockService)(nil).GetReplies), ctx, chatId)
}

// DeleteReply mocks base method
func (m *MockService) DeleteReply(ctx context.Context, chatId uint32, messageId string) error {
	ret := m.ctrl.Call(m, "DeleteReply", ctx, chatId, messageId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReply indicates an expected call of DeleteReply
func (mr *MockServiceMockRecorder) DeleteReply(ctx, chatId, messageId interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReply", reflect.TypeOf((*MockService)(nil).DeleteReply), ctx, chatId, messageId)
}
