// Code generated by MockGen. DO NOT EDIT.
// Source: ../telegram/service.go

// Package telegram is a generated GoMock package.
package telegram

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	telegram_bot_api_v4 "gopkg.in/telegram-bot-api.v4"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// SendMessage mocks base method
func (m *MockService) SendMessage(ctx context.Context, chatID int64, message string, messageID int) (int, error) {
	ret := m.ctrl.Call(m, "SendMessage", ctx, chatID, message, messageID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage
func (mr *MockServiceMockRecorder) SendMessage(ctx, chatID, message, messageID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockService)(nil).SendMessage), ctx, chatID, message, messageID)
}

// SendMessagePlainText mocks base method
func (m *MockService) SendMessagePlainText(ctx context.Context, chatID int64, message string, messageID int) (int, error) {
	ret := m.ctrl.Call(m, "SendMessagePlainText", ctx, chatID, message, messageID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessagePlainText indicates an expected call of SendMessagePlainText
func (mr *MockServiceMockRecorder) SendMessagePlainText(ctx, chatID, message, messageID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessagePlainText", reflect.TypeOf((*MockService)(nil).SendMessagePlainText), ctx, chatID, message, messageID)
}

// SendImageToGroup mocks base method
func (m *MockService) SendImageToGroup(ctx context.Context, image []byte, group int64) error {
	ret := m.ctrl.Call(m, "SendImageToGroup", ctx, image, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendImageToGroup indicates an expected call of SendImageToGroup
func (mr *MockServiceMockRecorder) SendImageToGroup(ctx, image, group interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendImageToGroup", reflect.TypeOf((*MockService)(nil).SendImageToGroup), ctx, image, group)
}

// SendDocumentToGroup mocks base method
func (m *MockService) SendDocumentToGroup(ctx context.Context, document []byte, extension string, group int64) error {
	ret := m.ctrl.Call(m, "SendDocumentToGroup", ctx, document, extension, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDocumentToGroup indicates an expected call of SendDocumentToGroup
func (mr *MockServiceMockRecorder) SendDocumentToGroup(ctx, document, extension, group interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDocumentToGroup", reflect.TypeOf((*MockService)(nil).SendDocumentToGroup), ctx, document, extension, group)
}

// SendKeyboard mocks base method
func (m *MockService) SendKeyboard(ctx context.Context, buttons []string, text string, chat int64) (int, error) {
	ret := m.ctrl.Call(m, "SendKeyboard", ctx, buttons, text, chat)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendKeyboard indicates an expected call of SendKeyboard
func (mr *MockServiceMockRecorder) SendKeyboard(ctx, buttons, text, chat interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendKeyboard", reflect.TypeOf((*MockService)(nil).SendKeyboard), ctx, buttons, text, chat)
}

// RegisterCommand mocks base method
func (m *MockService) RegisterCommand(command Command) {
	m.ctrl.Call(m, "RegisterCommand", command)
}

// RegisterCommand indicates an expected call of RegisterCommand
func (mr *MockServiceMockRecorder) RegisterCommand(command interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCommand", reflect.TypeOf((*MockService)(nil).RegisterCommand), command)
}

// RegisterCommandLet mocks base method
func (m *MockService) RegisterCommandLet(commandlet Commandlet) {
	m.ctrl.Call(m, "RegisterCommandLet", commandlet)
}

// RegisterCommandLet indicates an expected call of RegisterCommandLet
func (mr *MockServiceMockRecorder) RegisterCommandLet(commandlet interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCommandLet", reflect.TypeOf((*MockService)(nil).RegisterCommandLet), commandlet)
}

// requestAuthorisation mocks base method
func (m *MockService) requestAuthorisation(chat uint32, name string) (string, error) {
	ret := m.ctrl.Call(m, "requestAuthorisation", chat, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// requestAuthorisation indicates an expected call of requestAuthorisation
func (mr *MockServiceMockRecorder) requestAuthorisation(chat, name interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "requestAuthorisation", reflect.TypeOf((*MockService)(nil).requestAuthorisation), chat, name)
}

// pollAuthorisation mocks base method
func (m *MockService) pollAuthorisation(token string) (uint32, error) {
	ret := m.ctrl.Call(m, "pollAuthorisation", token)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// pollAuthorisation indicates an expected call of pollAuthorisation
func (mr *MockServiceMockRecorder) pollAuthorisation(token interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "pollAuthorisation", reflect.TypeOf((*MockService)(nil).pollAuthorisation), token)
}

// MockCommand is a mock of Command interface
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
}

// MockCommandMockRecorder is the mock recorder for MockCommand
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// CommandIdentifier mocks base method
func (m *MockCommand) CommandIdentifier() string {
	ret := m.ctrl.Call(m, "CommandIdentifier")
	ret0, _ := ret[0].(string)
	return ret0
}

// CommandIdentifier indicates an expected call of CommandIdentifier
func (mr *MockCommandMockRecorder) CommandIdentifier() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommandIdentifier", reflect.TypeOf((*MockCommand)(nil).CommandIdentifier))
}

// CommandDescription mocks base method
func (m *MockCommand) CommandDescription() string {
	ret := m.ctrl.Call(m, "CommandDescription")
	ret0, _ := ret[0].(string)
	return ret0
}

// CommandDescription indicates an expected call of CommandDescription
func (mr *MockCommandMockRecorder) CommandDescription() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommandDescription", reflect.TypeOf((*MockCommand)(nil).CommandDescription))
}

// RestrictToAuthorised mocks base method
func (m *MockCommand) RestrictToAuthorised() bool {
	ret := m.ctrl.Call(m, "RestrictToAuthorised")
	ret0, _ := ret[0].(bool)
	return ret0
}

// RestrictToAuthorised indicates an expected call of RestrictToAuthorised
func (mr *MockCommandMockRecorder) RestrictToAuthorised() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestrictToAuthorised", reflect.TypeOf((*MockCommand)(nil).RestrictToAuthorised))
}

// Execute mocks base method
func (m *MockCommand) Execute(update telegram_bot_api_v4.Update) {
	m.ctrl.Call(m, "Execute", update)
}

// Execute indicates an expected call of Execute
func (mr *MockCommandMockRecorder) Execute(update interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCommand)(nil).Execute), update)
}

// MockCommandlet is a mock of Commandlet interface
type MockCommandlet struct {
	ctrl     *gomock.Controller
	recorder *MockCommandletMockRecorder
}

// MockCommandletMockRecorder is the mock recorder for MockCommandlet
type MockCommandletMockRecorder struct {
	mock *MockCommandlet
}

// NewMockCommandlet creates a new mock instance
func NewMockCommandlet(ctrl *gomock.Controller) *MockCommandlet {
	mock := &MockCommandlet{ctrl: ctrl}
	mock.recorder = &MockCommandletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCommandlet) EXPECT() *MockCommandletMockRecorder {
	return m.recorder
}

// CanExecute mocks base method
func (m *MockCommandlet) CanExecute(update telegram_bot_api_v4.Update, state State) bool {
	ret := m.ctrl.Call(m, "CanExecute", update, state)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanExecute indicates an expected call of CanExecute
func (mr *MockCommandletMockRecorder) CanExecute(update, state interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanExecute", reflect.TypeOf((*MockCommandlet)(nil).CanExecute), update, state)
}

// Execute mocks base method
func (m *MockCommandlet) Execute(update telegram_bot_api_v4.Update, state State) {
	m.ctrl.Call(m, "Execute", update, state)
}

// Execute indicates an expected call of Execute
func (mr *MockCommandletMockRecorder) Execute(update, state interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCommandlet)(nil).Execute), update, state)
}

// NextState mocks base method
func (m *MockCommandlet) NextState(update telegram_bot_api_v4.Update, state State) string {
	ret := m.ctrl.Call(m, "NextState", update, state)
	ret0, _ := ret[0].(string)
	return ret0
}

// NextState indicates an expected call of NextState
func (mr *MockCommandletMockRecorder) NextState(update, state interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextState", reflect.TypeOf((*MockCommandlet)(nil).NextState), update, state)
}

// Fields mocks base method
func (m *MockCommandlet) Fields(update telegram_bot_api_v4.Update, state State) []string {
	ret := m.ctrl.Call(m, "Fields", update, state)
	ret0, _ := ret[0].([]string)
	return ret0
}

// Fields indicates an expected call of Fields
func (mr *MockCommandletMockRecorder) Fields(update, state interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fields", reflect.TypeOf((*MockCommandlet)(nil).Fields), update, state)
}
